# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmDeploy@0
  displayName: HELM LIST
  inputs:
    connectionType: Azure Resource Manager # Options: 'Azure Resource Manager', 'Kubernetes Service Connection', 'None' # Required  # Select 'Azure Resource Manager' to connect to an Azure Kubernetes Service by using Azure Service Connection. Select 'Kubernetes Service Connection' to connect to any Kubernetes cluster by using kubeconfig or Service Account
    azureSubscriptionEndpoint:  IAC - Connected Services # Required when connectionType = Azure Resource Manager  # Select an Azure subscription, which has your Azure Container Registry.
    azureResourceGroup:   csa-DEV-EUS-aks-rg
    kubernetesCluster:  csa-DEV-EUS-aks
    #useClusterAdmin:  # Optional  # Use cluster administrator credentials instead of default cluster user credentials.
    kubernetesServiceEndpoint:   # Required when connectionType = Kubernetes Service Connection  # Select a Kubernetes service connection.
    namespace: monitoring  # Specify K8 namespace to use. Use Tiller namespace can be specified in the advanced section of the task or by passing the --tiller-namespace option as argument.
    azureSubscriptionEndpointForACR:   # Required  # Select an Azure subscription, which has your Azure Container Registry.
    azureResourceGroupForACR:   # Required  # Select an Azure Resource Group, which has your Container Registry.
    azureContainerRegistry:   # Required  # Select an Azure Container Registry which will be used for pushing helm charts.
    command: ls # Options: 'create', 'delete', 'expose', 'get', 'init', 'install', 'login', 'logout', 'ls', 'package', 'rollback', 'save', 'upgrade', 'uninstall' # Required  # Select a helm command.
    chartType: Name # Options: 'Name', 'FilePath' # Required  # Select how you want to enter chart info. You can either provide name of the chart or folder/file path to the chart.
    chartName:   # Required when chartType == Name  # Chart reference to install, this can be a url or a chart name. For example, if chart name is 'stable/mysql', the task will run 'helm install stable/mysql'.
    chartPath:   # Required when chartType == FilePath || command == package  # Path to the chart to install. This can be a path to a packaged chart or a path to an unpacked chart directory. For example, if './redis' is specified the task will run 'helm install ./redis'.
    #version:  # Optional  # Specify the exact chart version to install. If this is not specified, the latest version is installed. Set the version on the chart to this semver version​
    #releaseName:  # Optional  # Release name. If unspecified, it will autogenerate one for you.
    #overrideValues:  # Optional  # Set values on the command line (can specify multiple or separate values with commas or newlines: key1=val1,key2=val2 or <br>key1=val1<br>key2=val2<br>). The task will construct the helm command by using these set values. For example, helm install --set key1=val1 ./redis.
    #valueFile:  # Optional  # Specify values in a YAML file or a URL. For example, specifying myvalues.yaml will result in 'helm install --values=myvals.yaml'.
    #destination:  # Optional  # Specify values in a YAML file or a URL.
    #canaryimage:  # Optional  # Use the canary Tiller image, the latest pre-release version of Tiller.
    #upgradetiller:  # Optional  # Upgrade if Tiller is already installed.
    #updatedependency:  # Optional  # Run helm dependency update before installing the chart. Update dependencies from 'requirements.yaml' to dir 'charts/' before packaging
    #save:  # Optional  # Save packaged chart to local chart repository (default true)​
    #install:  # Optional  # If a release by this name doesn't already exist, run an install​.
    #recreate:  # Optional  # Performs pods restart for the resource if applicable.
    #resetValues:  # Optional  # Reset the values to the ones built into the chart.
    #force:  # Optional  # Force resource update through delete/recreate if needed​
    #waitForExecution:  # Optional  # Block till command execution completes.
    arguments: --all # Optional  # Helm command options.
    #enableTls:  # Optional  # Enables using SSL between Helm and Tiller.
    caCert:   # Required when enableTls == true  # CA cert used to issue certificate for tiller and helm client.
    certificate:   # Required when enableTls == true  # Specify Tiller certificate or Helm client certificate
    privatekey:   # Required when enableTls == true  # Specify Tiller Key or Helm client key
    #tillernamespace:  # Optional  # Specify K8 namespace of tiller.
    #failOnStderr:  # Optional  # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream. Otherwise the task will rely on the exit code to determine failure.
    #publishPipelineMetadata:  # Optional  # If this is true, the task will collect and publish deployment metadata
    chartNameForACR:   # Required when command == save  # Chart name with which the chart will be stored in Azure Container Registry.
    chartPathForACR:   # Required when command == save  # Path to the chart directory.

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
